FROM alpine:3.16

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && apk update && apk add libcap

RUN cp /bin/ls /root/setcap_test && setcap cap_net_raw+ep /root/setcap_test
